jenkins-plugins:
  scale: 1
  metadata:
    plugins: |+
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm

jenkins-datavolume:
  scale: 1
  metadata:
    plugins: |+
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm

Loadbalancer:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
jenkins-primary:
  scale: 1
  metadata:
    plugins: |+
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm

