swarm-clients:
  image: "rancher/jenkins-swarm:v0.1.0"
  user: "root"
  labels:
    io.rancher.scheduler.global: true
    io.rancher.scheduler.affinity:host_label_soft: ci=worker
  external_links:
    - "jenkins-primary/jenkins-primary:jenkins-primary"
  environment:
    JENKINS_PASS: "${jenkins_pass}"
    JENKINS_USER: "${jenkins_user}"
    SWARM_EXECUTORS: "${swarm_executors}"
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/usr/bin/docker:/usr/bin/docker'
