etcd-init:
  image: rancher/etcd:v2.2.1
  labels:
    io.rancher.container.hostname_override: container_name
  ports:
    - '4001'
    - '2380'
    - '2379'
    - '7001'
  command: /opt/rancher/run.sh
