jenkins-plugins:
  image: rancher/jenkins-plugins:v0.1.1
jenkins-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - chown
  - -R
  - 1000:1000
  - /var/jenkins_home
  image: busybox
  volumes:
  - /var/jenkins_home
Loadbalancer:
  ports:
  - 2080:8080
  tty: true
  image: rancher/load-balancer-service
  links:
  - jenkins-primary:jenkins-primary
  stdin_open: true
jenkins-primary:
  ports:
  - 8080:8080/tcp
  labels:
    io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
    io.rancher.container.hostname_override: container_name
  entrypoint:
  - /usr/share/jenkins/rancher/jenkins.sh
  image: jenkins:1.642.2
  volumes_from:
  - jenkins-plugins
  - jenkins-datavolume
