name: Jenkins
description: |
  # This is a test catalog
version: 1
category: CI-CD
maintainer: CLEO
license: TEST-License
projectURL: https://github.com/mimmel/rancher.git


.catalog:
  name: jenkins
  version: 1
  description: Some Discription
  minimum_rancher_version: .1
  questions:
    - variable: name
      label: Name
      description: | Name of instance
      default: Cleo Jenkins
      required: True
      type: # How the questions are formatted and types of response expected
