etcd:
  image: cloudnautique/etcd:v2.3.6-12
  restart: always
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: data,healthcheck
    io.rancher.container.hostname_override: container_name
  environment:
    ETCD_DATA_DIR: /data
    ETCDCTL_ENDPOINT: http://etcd:2379
    RANCHER_DEBUG: ${DEBUG}
  links:
  - data
  volumes_from:
    - data
healthcheck:
  net: container:etcd
  entrypoint: /usr/local/bin/giddyup health --check-command /healthcheck.sh
  image: cloudnautique/etcd:v2.3.6-12
  volumes_from:
    - data
# containerize data volume to enable restarts and upgrades
data:
  image: busybox
  entrypoint: /bin/true
  net: none
  volumes:
      - /data
  labels:
    io.rancher.container.start_once: 'true'
